name: Run Job Alert Script

on:
  schedule:
    - cron: "*/10 * * * *"  # kas 10 minu훾i킬
  workflow_dispatch:        # leid탑ia rankiniu b큰du paleisti

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set secret env var
      run: echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

    - name: Run script
      run: python job_vacancy_alert.py
